#:kivy 1.0.9

GridLayout:
    rows: 4
    cols: 2
    Label:
        text: 'Shape'
    TextInput:
        multiline: False
        id: shapeI
        #on_text: p.select(self.text)
        on_text: shapeI_cb
    Button:
        text: 'Surface'
    Button:
        text: 'Volume'
    Button:
        text: 'Mass'
    Button:
        text: 'Report'
    Label:
        text: 'Output'
    Label:
        text: ''